services:
  - type: web
    name: tartanmart-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webapps.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: webapps.settings
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://tartanmart-frontend.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: tartanmart-db
          property: connectionString
