services:
  - type: web
    name: tartanmart-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      echo "Running migrations..."
      python manage.py makemigrations cmumarketplace --noinput
      python manage.py migrate --noinput
      echo "Migrations completed"
    startCommand: gunicorn webapps.wsgi:application
    healthCheckPath: /health/
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_SETTINGS_MODULE
        value: webapps.settings
      - key: DJANGO_DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: tartan-mart-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://tartanmart-frontend.netlify.app
      - key: CSRF_TRUSTED_ORIGINS
        value: https://tartanmart-frontend.netlify.app
      - key: SITE_URL
        value: https://tartanmart-frontend.netlify.app
      - key: SESSION_COOKIE_DOMAIN
        value: tartan-mart-backend.onrender.com
      - key: USE_S3
        value: True
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_STORAGE_BUCKET_NAME
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: tartanmart-db
          property: connectionString
